[package]
name = "nalarvo-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
nalarvo-contracts = { path = "../contracts" }
reqwest.workspace = true
thiserror.workspace = true

[dev-dependencies]
nalarvo-local-api = { path = "../local-api" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
axum.workspace = true
