[package]
name = "nalarvo-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "nalarvo"
path = "src/main.rs"

[dependencies]
nalarvo-client = { path = "../client" }
clap = { workspace = true, features = ["env"] }
tokio.workspace = true
url.workspace = true
