[package]
name = "nalarvo-local-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
nalarvo-contracts = { path = "../contracts" }
axum.workspace = true
serde.workspace = true

[dev-dependencies]
http-body-util.workspace = true
tokio.workspace = true
tower = { workspace = true, features = ["util"] }
